# Generated by Django 4.2.8 on 2025-07-21 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('document_data', models.JSONField(blank=True, default=dict)),
                ('assignatures', models.JSONField(blank=True, default=dict)),
                ('remarks', models.JSONField(blank=True, default=dict, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='template.template')),
            ],
        ),
    ]
