# Generated by Django 4.2.8 on 2025-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='to_route',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
