# Generated by Django 4.2.8 on 2025-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_to_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='isupload',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
