# Generated by Django 4.2.8 on 2025-12-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the candidate', max_length=255)),
                ('location', models.CharField(help_text='Location of the candidate', max_length=255)),
                ('age', models.IntegerField(help_text='Age of the candidate')),
                ('image', models.ImageField(help_text='Image for the candidate', upload_to='candidates/')),
                ('votes', models.IntegerField(default=0, help_text='Number of votes received by the candidate')),
                ('voters', models.JSONField(default=list, help_text='List of voter names who voted for this candidate')),
            ],
        ),
    ]
