# Generated by Django 4.2.8 on 2025-04-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='inital',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='project',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
