# Generated by Django 4.2.8 on 2025-04-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_designation_useraccount_inital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
