# Generated by Django 4.2.8 on 2025-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='division',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='acc_lvl',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
