# Generated by Django 4.2.8 on 2025-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_title', models.CharField(blank=True, max_length=255)),
                ('requestor_name', models.CharField(blank=True, max_length=255)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
