# Generated by Django 4.2.8 on 2025-05-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_date_booking_end_date_booking_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='booking_attachments/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
