# Generated by Django 4.2.8 on 2025-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_user_booking_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attachment',
            field=models.CharField(blank=True, max_length=1012, null=True),
        ),
    ]
