# Generated by Django 4.2.8 on 2025-12-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the performer', max_length=255)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the performer (optional)', null=True, upload_to='performers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater', models.CharField(help_text='Name of the rater', max_length=255)),
                ('ratings', models.JSONField(default=list, help_text='List of scores [Talent, Creativity, Stage Presence, Relevance of ICT, Time Adherence]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rate.performer')),
            ],
            options={
                'unique_together': {('performer', 'rater')},
            },
        ),
    ]
