# Generated by Django 4.2.8 on 2025-07-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
