# Generated by Django 4.2.8 on 2025-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('about', models.TextField()),
                ('employee', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
