# Generated by Django 4.2.8 on 2025-04-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.JSONField(default=list),
        ),
    ]
