from django.db import models

# Create your models here.
class Document(models.Model):
    # ID is auto-generated by Django by default
    title = models.CharField(max_length=200)
    url = models.URLField(max_length=500)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.JSONField(default=list, blank=True)  # Store tags as a JSON list
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-date_created']