# Generated by Django 4.2.8 on 2025-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('lgu_agency', models.CharField(max_length=255, verbose_name='LGU/Agency')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_date'],
            },
        ),
    ]
