# Generated by Django 4.2.8 on 2025-06-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
